// Copyright Jay Conrod. All rights reserved.

// This file is part of CodeSwitch. Use of this source code is governed by
// the 3-clause BSD license that can be found in the LICENSE.txt file.

// This test checks whether we can properly handle exceptions thrown in
// catch handlers. The newly thrown exception should replace the original
// exception, and the finally handler should still be executed.

var inner-finally-executed = false
var catch-executed = false
var outer-finally-executed = false

def f =
  try
    try
      try
        return
      finally
        inner-finally-executed = true
    catch (_)
      catch-executed = true
      {}
  finally
    outer-finally-executed = true

def main =
  f
  if (!inner-finally-executed || catch-executed || !outer-finally-executed)
    throw Exception()
